definitions:
  types.Email:
    properties:
      email:
        type: string
      id:
        type: integer
      user_id:
        type: integer
    type: object
  types.EmailIDs:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  types.EmailRequest:
    properties:
      emails:
        items:
          type: string
        type: array
    required:
    - emails
    type: object
  types.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  types.Friend:
    properties:
      first_name:
        type: string
      friend_id:
        type: integer
      last_name:
        type: string
    required:
    - first_name
    type: object
  types.Friends:
    properties:
      friends_ids:
        items:
          type: integer
        type: array
    required:
    - friends_ids
    type: object
  types.Friendship:
    properties:
      id_first_friend:
        type: integer
      id_second_friend:
        type: integer
    required:
    - id_first_friend
    - id_second_friend
    type: object
  types.Friendships:
    properties:
      friends:
        items:
          $ref: '#/definitions/types.Friendship'
        type: array
    type: object
  types.Name:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    required:
    - first_name
    type: object
  types.SuccessResponse:
    properties:
      message:
        example: OK
        type: string
    type: object
  types.User:
    properties:
      age:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      nationality:
        type: string
    required:
    - first_name
    type: object
  types.UserInfo:
    properties:
      age:
        type: integer
      emails:
        items:
          type: string
        type: array
      first_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      last_name:
        type: string
      nationality:
        type: string
    required:
    - first_name
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    get:
      description: Get users information with emails
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.UserInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get all users details
      tags:
      - people
    post:
      consumes:
      - application/json
      description: process POST req for add user
      parameters:
      - description: first name and second name
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.Name'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            format: int64
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process POST req for add user
      tags:
      - people
  /api/v1/users/:id:
    delete:
      consumes:
      - application/json
      description: process DELETE request for deleting user`s info
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process DELETE request for deleting user`s info
      tags:
      - people
    get:
      description: Get user information with emails by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get user details
      tags:
      - people
    put:
      consumes:
      - application/json
      description: process PUT request for edite user`s info
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: user`s info
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process PUT request for edite user`s info
      tags:
      - people
  /api/v1/users/:id/emails:
    get:
      description: Get all user`s emails
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Email'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get all user`s emails
      tags:
      - people
    post:
      consumes:
      - application/json
      description: process POST req for add user`s emails
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: list of user`s emails
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process POST req for add user`s emails
      tags:
      - people
  /api/v1/users/:id/friends:
    delete:
      consumes:
      - application/json
      description: process DELETE request to delete friendships (one or more)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: list of friendships
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.Friendships'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process DELETE request to delete friendships (one or more)
      tags:
      - people
    get:
      consumes:
      - application/json
      description: Get all user`s friends
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Friend'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get all user`s friends
      tags:
      - people
    post:
      consumes:
      - application/json
      description: process POST req for add user`s friends
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: list of user`s friends
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.Friends'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process POST req for add user`s friends
      tags:
      - people
  /api/v1/users/emails:
    delete:
      consumes:
      - application/json
      description: process DELETE request to delete emails (one or more)
      parameters:
      - description: list email`s ids
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/types.EmailIDs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: process DELETE request to delete emails (one or more)
      tags:
      - people
swagger: "2.0"
